### ISSUE TITLE
Comments section is DISQUS-ting

### ISSUE THREAD

**Issue by heejongahn** [heejongahn/hjlog#24]
That was lame joke but contains some amount of truth. Current self-powered comments section is hard to notice and we cannot identify who wrote the comments. Let's just use DISQUS.

**Comment by shimazing** [comment]
https://hjlogme.disqus.com/admin/settings/general/
기록용 호호 나만 쓸수있지롱

**Comment by shimazing** [comment]
디비 + 입력 폼 + 템플릿

**Comment by heejongahn** [comment]
:+1:

**Comment by heejongahn** [comment]
#25 풀 리퀘스트로 해결되었습니다. :tada:

**Comment by shimazing** [comment]
야호!
