### ISSUE TITLE
Disqus로 연동되는 부분의 댓글 작성자 이름이 제대로 나오지 않는 경우 있음

### ISSUE THREAD

**Issue by scvgoe** [heejongahn/hjlog#42]
![2016-07-03 10 04 17](https://cloud.githubusercontent.com/assets/10363679/16545586/553e2798-416a-11e6-9391-b92ce9c4a964.png)

%(post)s 댓글 

라고 나옴

**Comment by scvgoe** [comment]
니 코드가 아니려나...

**Comment by heejongahn** [comment]
@shimazing 

나도 저거 거슬리긴 했는데, 어쩔 수 없는거인지 아니면 `disqus_config`를 제대로 설정 안 해줘서 그런건지 모르겠네. 시간 날 때 확인해봐주세요~

**Comment by shimazing** [comment]
댓글이 여러 개 달린 포스트에 대해서 저렇게 나오는 것 확인
disqus 자체 버그라고 추측하고 있..
Language 설정을 영어로 바꾸니까 정상으로 나오길래 일단 그렇게 바꿔놨지 ..ㅎㅎㅎㅎ

https://disqus.com/home/channel/discussdisqus/discussion/channel-discussdisqus/posts_instead_of_the_number_of_comments_in_latast_discussions/ 
이것도 혹시몰라 올려뒀지

**Comment by heejongahn** [comment]
이거 해결된 것 맞나요? 나는 그대로 나오는데 disqus 언어 설정이 각 유저별로 적용되는건가? @shimazing

**Comment by shimazing** [comment]
disqus에서 버그 확인할 수 있게 다시 원래대로 해놨으요 @heejongahn

**Comment by heejongahn** [comment]
disqus에서 처리 안 할 것 같으면 일단 영어로 다시 바꾸는게 어떨까용

**Comment by shimazing** [comment]
바꿨어용 ___ 역시  빨리 안고쳐주는구만 흥흥이다

**Comment by heejongahn** [comment]
그럼 일단 이 이슈는 닫겠습니다. 혹시 추가로 업데이트되는게 있으면 다시 열어주세요 😄
