### ISSUE TITLE
로그인 후에 원래 보던 페이지로 돌아가면 좋을 것 같음

### ISSUE THREAD

**Issue by shimazing** [heejongahn/hjlog#43]
지금은 로그인 후 홈으로 가는데 
방금 글 읽다가 로그인하니까 글 다시 찾아가야해서 약간의 불편___

**Comment by heejongahn** [comment]
있으면 좋겠네요! [이 링크](http://flask.pocoo.org/snippets/63/) 를 참조해서 직접 추가해보시죠 ㅎㅎㅎ
