### ISSUE TITLE
수식 렌더링

### ISSUE THREAD

**Issue by heejongahn** [heejongahn/hjlog#49]
@shimazing 이 요새 공부하는 내용들을 블로그 글로 남기기 위해선 수식을 넣을 방법이 필요합니다. 매번 이미지로 만들어서 캡쳐하는거 말고 마크다운처럼 특정 문법으로 쓰면 (아마 레이텍?) 알아서 자바스크립트로 렌더링 되게..

목마른 사람이 우물을 파는 법이라고 하진이가 이 이슈를 책임지고 해결하는걸로! 일단 필요한 스펙을 정의하는데부터 시작해보면 될 것 같아요.

**Comment by shimazing** [comment]
역시 빠르시군요 이슈를 만들었다니! 
오늘 밤부터 함 알아보는걸로 하죵...게으름뱅이라서 항상 미안해요!

아이목말라 우물을파야겠네

**Comment by heejongahn** [comment]
@shimazing 해야될 일 다 끝난거면 닫아주세요!
